name: Zota
options:
  bundleIdPrefix: com.zoo.zota
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

targets:
  Zota:
    type: application
    platform: macOS
    sources:
      - path: Zota
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zoo.zota
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        SWIFT_VERSION: "5.10"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ENABLE_APP_SANDBOX: false
        ENABLE_HARDENED_RUNTIME: false
        CODE_SIGN_IDENTITY: "-"
    entitlements:
      path: Zota/Zota.entitlements
      properties:
        com.apple.security.network.client: true

  ZotaTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ZotaTests
    dependencies:
      - target: Zota
    settings:
      base:
        SWIFT_VERSION: "5.10"
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGN_IDENTITY: "-"
